### ISSUE TITLE
Interpolating variables followed by other letters/characters

### ISSUE THREAD

**Issue by jimeUWOshkosh** [rbwohlfarth/ETL-Pipeline#1]
Ubuntu 18.04
system perl (v5.26.1) and perlbrew 5.28.0

Trying to install ETL::Pipeline (metacpan says 2.02, code says 2.03) but it fails
'make test' because of multiple

Use of uninitialized value $action:: in concatenation (.) or string at
... Pipeline.pm line 1120.

1120:   $class = "ETL::Pipeline::$action::$class";

Changed to
   $class = "ETL::Pipeline::${action}::$class";

**Comment by rbwohlfarth** [comment]
Fixed by commit e825406ecc5fa9a10cf8208736ff213aa65c7854.
